### PR TITLE
Release/5.0.1

### LINKED ISSUE #172: Recent changes to **Matrix** break installed SeuratObject
Hi,

As you might know, the latest versions of **Matrix** have introduced changes that break a number of packages on machines where they were installed before **Matrix** got updated.

One of the victims is the **SeuratObject** package:
```
> library(SeuratObject)
> LogMap(y=letters)
Error in validObject(.Object) : 
  invalid class "LogMap" object: superclass "mMatrix" not defined in the environment of the object's class
```
This happens on any machine where **SeuratObject** got installed before the latest **Matrix** (1.6-3) got into the wild and landed on the machine.

Unfortunately, the approach of the **Matrix** maintainers is to simply assume that people will proactively reinstall packages affected by the changes they're doing. Even though it's really hard or even impossible for the end users or system admins to know what packages exactly need reinstallation.

However, the situation would greatly improve if **SeuratObject**'s version was bumped and the bumped version resubmitted to CRAN. The new version would then naturally propagate to the user machine which in turn would trigger a reinstallation.

I'm kindly asking if you would consider doing that.

Note that 20+ Bioconductor packages depend directly or indirectly on **SeuratObject** and are currently broken on any machine where the latest **Matrix** has landed.

FWIW [here](https://github.com/bwlewis/irlba/issues/70#issuecomment-1814697684) is another CRAN package broken by the recent changes to **Matrix**.

Thanks,

H.

### PR DESCRIPTION
**Pull request by mojaveazure**
- [x]  Bump version
- [x] Update CRAN comments
- [x] Update changelog
- [x] Win-builder

resolves #172

### CODE REVIEW

**Review by Gesmira — APPROVED** [review]

File: R/seurat.R [hunk 1]
```diff
@@ -2465,13 +2474,20 @@ SetAssayData.Seurat <- function(
...
+    )
+    layer <- slot
+  }
   object <- UpdateSlots(object = object)
   assay <- assay %||% DefaultAssay(object = object)
   object[[assay]] <- SetAssayData(
     object = object[[assay]],
     layer = layer,
     new.data = new.data,
-    slot = slot,
```
Comment (Gesmira) [inline R/seurat.R:2474]: This now fails
pbmc3k <- LoadData('pbmc3k')
pbmc3k <- SetAssayData(
    object = pbmc3k,
    assay = "RNA",
    slot = "data",
    new.data = pbmc3k[["RNA"]]$data
)
